src/MotorCycleDB/Models/Chassis.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MotorCycleDB.Models
{
    public class Chassis
    {
        public int Weight { get; set; }
        public int SeatHeight { get; set; }
        public int Length { get; set; }

    }
}

src/MotorCycleDB/Models/Engine.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MotorCycleDB.Models
{
    public class Engine
    {
        public int Cylinders { get; set; }
        public string Configuration { get; set; }
        public int Displacement { get; set; }

    }
}

src/MotorCycleDB/Models/Mfg.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MotorCycleDB.Models
{
    public class Mfg
    {
        public string Name { get; set; }
        //public string Role { get; set; }
    }
}

src/MotorCycleDB/Models/Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MotorCycleDB.Models
{
    public class Model
    {
        public string Name { get; set; }
        public decimal Displacement { get; set; }
    }
}

src/MotorCycleDB/Models/MotorCycleDBContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MotorCycleDB.Models
{
    public class MotorCycleDBContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public MotorCycleDBContext() : base("name=MotorCycleDBContext")
        {
        }

        public System.Data.Entity.DbSet<MotorCycleDB.Models.Motorcycle> Motorcycles { get; set; }
    }
}

src/MotorCycleDB/Models/Motorcycle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace MotorCycleDB.Models
{
    public class Motorcycle
    {
        // Set up properties for Motorcycles
        public int Id { get; set; }
        public string Mfg { get; set; }
        public string ModelId { get; set; }
        public int ModelYear { get; set; }
        public string Engine { get; set; }
        public int Horsepower { get; set; }
        public int Torque { get; set; }
        public int? Weight { get; set; }
        public string Style { get; set; }
        public string Description { get; set; }

     

            // Add DB context class for communication with database
        //public class MotorcycleDBContext : DbContext
        //{
        //    public DbSet<Motorcycle> Motorcycles { get; set; }
        //}

    }
}

src/MotorCycleDB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MotorCycleDB.Models;

namespace MotorCycleDB.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/MotorCycleDB/Controllers/MCDBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MotorCycleDB.Controllers
{
    public class MCDBController : Controller
    {
        // Directs the browser to the "Home or index" page
        public ActionResult Index()
        {
            return View();
        }

    }
}

src/MotorCycleDB/Controllers/MotorcycleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MotorCycleDB.Models;
using MotorCycleDB.Data;

// Motorcycle Controller class.  Directs the app to the Create, Edit, Delete, Details, and Index (MC list) views.

namespace MotorCycleDB.Controllers
{
    public class MotorcycleController : Controller
    {
        private MotorCycleDBContext db = new MotorCycleDBContext();

        // Displays list of all Motorcycles in database
        public ActionResult Index()
        {
            return View(db.Motorcycles.ToList());
        }

        // Displays detail page of selected motorcycle
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Motorcycle motorcycle = db.Motorcycles.Find(id);
            if (motorcycle == null)
            {
                return HttpNotFound();
            }
            return View(motorcycle);
        }

        // Displays the Create motorcycle form
        public ActionResult Create()
        {
            return View();
        }

        //Create new motorcycle entry
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Mfg,ModelId,ModelYear,Engine,Horsepower,Torque,Weight,Style,Description")] Motorcycle motorcycle)
        {
            if (ModelState.IsValid)
            {
                db.Motorcycles.Add(motorcycle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(motorcycle);
        }

        // returns edit view for selected motorcycle
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Motorcycle motorcycle = db.Motorcycles.Find(id);
            if (motorcycle == null)
            {
                return HttpNotFound();
            }
            return View(motorcycle);
        }

        // Saves changes to motorcycle record
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Mfg,ModelId,ModelYear,Engine,Horsepower,Torque,Weight,Style,Description")] Motorcycle motorcycle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(motorcycle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(motorcycle);
        }

        // Pulls up the Delete view
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Motorcycle motorcycle = db.Motorcycles.Find(id);
            if (motorcycle == null)
            {
                return HttpNotFound();
            }
            return View(motorcycle);
        }

        // Actually deletes the Motorcycle record from the database

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Motorcycle motorcycle = db.Motorcycles.Find(id);
            db.Motorcycles.Remove(motorcycle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/MotorCycleDB/Views/Entries/Add.cshtml
@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

src/MotorCycleDB/Views/Entries/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

src/MotorCycleDB/Views/Entries/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

src/MotorCycleDB/Views/Entries/Index.cshtml
@model MotorCycleDB.Models.Motorcycle[]
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<h2>@ViewBag.Title</h2>

<div class="row">
    @foreach (var motorcycle in Model)
    {
        <div class="col-md-3">
            <h4>@Html.ActionLink(motorcycle.DisplayBike, "Detail", new { id = motorcycle.Id })</h4>
        </div>
    }
</div>

src/MotorCycleDB/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/MotorCycleDB/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/MotorCycleDB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Motorcycle DB";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

src/MotorCycleDB/Views/MCDB/Contact.cshtml
@model MotorCycleDB.Models.Motorcycle[]
@{
    ViewBag.Title = "Contact";
}

<h2>Contact</h2>

src/MotorCycleDB/Views/MCDB/Index.cshtml
@model MotorCycleDB.Models.Motorcycle[]
@{
    ViewBag.Title = "Home";
}



<h2>MCDB</h2>

<div class="row">
    <!--This is the Home page view. --> 
    
        <div class="col-md-3">
            <h4>Welcome to the Motorcycle Database.  </h4>
        </div>
        <div class="col-md-3">Feel free to look at the list.  If you have a model that needs to be added, feel free.  Please ensure that the data is accurate.</div>
    
</div>

src/MotorCycleDB/Views/MCDB/MotorcycleList.cshtml
@{
    ViewBag.Title = "MotorcycleList";
}

<h2>MotorcycleList</h2>

src/MotorCycleDB/Views/Motorcycle/Create.cshtml
@model MotorCycleDB.Models.Motorcycle

@{
    ViewBag.Title = "Add New";
}

<h2>Add New Motorcycle</h2>
<!-- this is the page for creating a new motorcycle entry -->

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Mfg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mfg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mfg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModelId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModelId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModelYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModelYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModelYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Engine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Engine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Engine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Horsepower, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Horsepower, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Horsepower, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Torque, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Torque, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Torque, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Style, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Style, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Style, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/MotorCycleDB/Views/Motorcycle/Delete.cshtml
@model MotorCycleDB.Models.Motorcycle

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this Motorcycle?</h3>
<div>
    <!----This is the page for deleting a motorcycle record.  It shows the details of the entry as well. -->
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mfg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mfg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModelId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModelId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModelYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModelYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Engine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Engine)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Horsepower)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Horsepower)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Torque)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Torque)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Style)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Style)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

src/MotorCycleDB/Views/Motorcycle/Details.cshtml
@model MotorCycleDB.Models.Motorcycle

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.Mfg) @Html.DisplayFor(model => model.ModelId) Details</h2>

<div>
   <!---- This page shows all of the details for the motorcycle record. -->
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mfg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mfg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModelId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModelId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModelYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModelYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Engine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Engine)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Horsepower)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Horsepower)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Torque)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Torque)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Style)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Style)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/MotorCycleDB/Views/Motorcycle/Edit.cshtml
@model MotorCycleDB.Models.Motorcycle

@{
    ViewBag.Title = "Edit";
}

<h2>Edit @Html.DisplayFor(model => model.Mfg) @Html.DisplayFor(model => model.ModelId)</h2>

<!-- this page uses a form to pull the details of a record for editing and allows any of the info to be updated. -->
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Motorcycle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Mfg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mfg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mfg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModelId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModelId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModelYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModelYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModelYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Engine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Engine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Engine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Horsepower, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Horsepower, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Horsepower, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Torque, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Torque, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Torque, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Style, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Style, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Style, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/MotorCycleDB/Views/Motorcycle/Index.cshtml
@model IEnumerable<MotorCycleDB.Models.Motorcycle>

@{
    ViewBag.Title = "Motorcycle List";
}

<!-- This page displays all records in the motorcycle database.  Uses a table format, one record per row. -->
<h2>Motorcycle List</h2>

<p>
    @Html.ActionLink("Add New", "Create")
</p>
<table class="table table-hover table-responsive">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Mfg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModelId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModelYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Engine)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Horsepower)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Torque)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Style)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
        // Uses Url.Action to pass a route ti the window.location.  Makes each row in the list a link to the details page.
        <tr onclick="window.location='@Url.Action("Details", new { id = item.Id })';">

            <td>
                @Html.DisplayFor(modelItem => item.Mfg)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModelId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModelYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Engine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Horsepower)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Torque)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Style)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}

</table>

src/MotorCycleDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Motorcycle Database</title>
    @Styles.Render("~/Content/css") 
    @Styles.Render("~/Content/Site.css")<!-- Added directive to use additional styling-->
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Motorcycle Database Home", "Index", "MCDB", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("MC List", "Index", "Motorcycle")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Motorcycle Database</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>